# Site settings
title: Way of Thinking
email: hello@wayofthinking.net
description: > # this means to ignore newlines until "baseurl:"
  Way of Thinking, the legal entity of Els Ceulemans and Thierry de Pauw.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wayofthinking.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
